---
name: "Summarizer"
dataIns:
  - name: "inputFile"
    type: "string"
    source: "inputFile"

  - name: "provider"
    type: "string"
    source: "provider"

  - name: "outputBucket"
    type: "string"
    source: "outputBucket"

  - name: "inputBucket"
    type: "string"
    source: "inputBucket"

  - name: "inputType"
    type: "string"
    source: "inputType"

workflowBody:
- function:
    name: "summarise"
    type: "summariseType"
    dataIns:
      - name: "inputFile"
        type: "string"
        source: "Summarizer/inputFile"
      - name: "provider"
        type: "string"
        source: "Summarizer/provider"
      - name: "outputBucket"
        type: "string"
        source: "Summarizer/outputBucket"
      - name: "inputBucket"
        type: "string"
        source: "Summarizer/inputBucket"
      - name: "inputType"
        type: "string"
        source: "Summarizer/inputType"
    dataOuts:
      - name: "outputfile"
        type: "string"
      - name: "timeToSummarise"
        type: "number"
      - name: "totalExecutionTime"
        type: "number"
      - name: "ratio"
        type: "number"
      - name: "executedOnProvider"
        type: "string"
      - name: "calledByProvider"
        type: "string"
    properties:
      - name: "resource"
        value: "https://us-central1-crafty-tractor-401010.cloudfunctions.net/java-summarizer"
dataOuts:
  - name: "outputfile"
    type: "string"
    source: "summarise/outputfile"
