---
name: "Summarizer"
dataIns:
- name: "inputFile"
  type: "string"
  source: "inputFile"

- name: "provider"
  type: "string"
  source: "provider"

- name: "outputBucket"
  type: "string"
  source: "outputBucket"

- name: "inputBucket"
  type: "string"
  source: "inputBucket"

- name: "inputType"
  type: "string"
  source: "inputType"

workflowBody:
- function:
    name: "summarise"
    type: "summariseType"
    dataIns:
      - name: "inputFile"
        type: "string"
        source: "Summarizer/inputFile"
      - name: "provider"
        type: "string"
        source: "Summarizer/provider"
      - name: "outputBucket"
        type: "string"
        source: "Summarizer/outputBucket"
      - name: "inputBucket"
        type: "string"
        source: "Summarizer/inputBucket"
      - name: "inputType"
        type: "string"
        source: "Summarizer/inputType"
    dataOuts:
      - name: "outputfile"
        type: "string"
    properties:
      - name: "resource"
        value: "https://java-summarizer-sto6cpt45q-uc.a.run.app"